import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'general.yes': 'Yes',
          'general.no': 'No',
          'general.close': 'Close',
          'general.cancel': 'Cancel',
          'general.save': 'Save',
          'general.save_changes': 'Save Changes?',
          'general.disable': 'Disable',
          'general.enable': 'Enable',
          'general.activate': 'Activate',
          'general.reset': 'Reset',
          'general.turn_off_notifiaction': 'Turn off notification?',
          'general.edit_notification_time': 'Edit notification time',
          'general.activate_notifications': 'Activate notifications',
          'general.please_enable_notifications_in_the_general_settings_of_your_device':
              'Please enable notifications in the general settings of your device',
          'general.when_would_you_like_to_be_notified':
              'When would you like to be notified?',
          'general.daily': 'Daily',
          'general.monday': 'Monday',
          'general.tuesday': 'Tuesday',
          'general.wednesday': 'Wednesday',
          'general.thursday': 'Thursday',
          'general.friday': 'Friday',
          'general.saturday': 'Saturday',
          'general.sunday': 'Sunday',
          'app.title': 'Prayers',
          'settings.title': 'Settings',
          'settings.dark_mode': 'Dark Mode',
          'settings.language': 'Language',
          'settings.choose_language': 'Choose a language',
          'agpeya.subtitle': 'The prayer of the seven canonical hours',
          'agpeya.title': 'Agpeya',
          'agpeya.introductory_prayer': 'Introductory Prayer',
          'agpeya.come_and_let_us_worship': 'Come, let us worship',
          'agpeya.psalms': 'Psalms',
          'agpeya.gospel_and_litany': 'Gospel and Litany',
          'agpeya.trisagion_and_creed': 'Trisagion and Creed',
          'agpeya.concluding_prayers': 'Concluding Prayers',
          'agpeya.hour_introduction': 'Hour Introduction',
          'agpeya.first_service': 'First Service',
          'agpeya.second_service': 'Second Service',
          'agpeya.third_service': 'Third Service',
          'agpeya.conclusion': 'Conclusion',
          'agpeya.introduction': 'Introduction',
          'agpeya.pray_now': 'Pray now',
          'agpeya.activate_this_prayer_again': 'Activate this prayer again?',
          'agpeya.first_hour.title': 'First Hour',
          'agpeya.first_hour.titleLatin': 'Prime',
          'agpeya.first_hour.subtitle':
              'In commemoration of the resurrection of Jesus Christ and to give thanks for a new day.',
          'agpeya.first_hour.description':
              'Instituted to commemorate the hour at which our Lord Jesus Christ rose from the dead. To be read in the morning, to give thanks to God for the beginnign of a new day, and to glorify Him for His resurrection.',
          'agpeya.first_hour.latinNumber': 'I',
          'agpeya.first_hour.icon': 'assets/images/first_hour.png',
          'agpeya.first_hour.colorVibrant1': '95383D',
          'agpeya.first_hour.colorVibrant2': '84529D',
          'agpeya.first_hour.colorDark': '442218',
          'agpeya.first_hour.colorLight': '442218',
          'agpeya.third_hour.title': 'Third Hour',
          'agpeya.third_hour.titleLatin': 'Terce',
          'agpeya.third_hour.subtitle':
              'In commemoration of the outpouring of the Spirit and the hour in which Jesus Christ was condemned.',
          'agpeya.third_hour.description':
              'Instituted to commemorate the hour at which our Lord Jesus Christ was condemned. Also, at this hour the Holy Spririt came down on the disciples.',
          'agpeya.third_hour.latinNumber': 'III',
          'agpeya.third_hour.icon': 'assets/images/third_hour.png',
          'agpeya.third_hour.colorVibrant1': '953622',
          'agpeya.third_hour.colorVibrant2': 'C8491C',
          'agpeya.third_hour.colorDark': '576959',
          'agpeya.third_hour.colorLight': 'FFFF83',
          'agpeya.sixth_hour.title': 'Sixth Hour',
          'agpeya.sixth_hour.titleLatin': 'Sext',
          'agpeya.sixth_hour.subtitle':
              'In commemoration of the crucifixion of Jesus Christ at noon.',
          'agpeya.sixth_hour.description':
              'Instituted to commemorate the crucifixion of our Lord Jesus Christ.',
          'agpeya.sixth_hour.latinNumber': 'VI',
          'agpeya.sixth_hour.icon': 'assets/images/sixth_hour.png',
          'agpeya.sixth_hour.colorVibrant1': '888D35',
          'agpeya.sixth_hour.colorVibrant2': 'D05D5A',
          'agpeya.sixth_hour.colorDark': '441A1A',
          'agpeya.sixth_hour.colorLight': 'D9B46B',
          'agpeya.ninth_hour.title': 'Ninth Hour',
          'agpeya.ninth_hour.titleLatin': 'None',
          'agpeya.ninth_hour.subtitle':
              'In commemoration of the hour of death when Jesus Christ gave up his spirit.',
          'agpeya.ninth_hour.description':
              'Instituted to commemorate the hour of death of our Lord Jesus Christ in the flesh, and the right-hand thief who found favour in His eyes.',
          'agpeya.ninth_hour.latinNumber': 'IX',
          'agpeya.ninth_hour.icon': 'assets/images/ninth_hour.png',
          'agpeya.ninth_hour.colorVibrant1': 'AD5025',
          'agpeya.ninth_hour.colorVibrant2': '931002',
          'agpeya.ninth_hour.colorDark': '6B3012',
          'agpeya.ninth_hour.colorLight': 'DCC4A3',
          'agpeya.eleventh_hour.title': 'Eleventh Stunde',
          'agpeya.eleventh_hour.titleLatin': 'Vespers',
          'agpeya.eleventh_hour.subtitle':
              'In commemoration of the taking down of Jesus Christ from the cross and the anointing of His body.',
          'agpeya.eleventh_hour.description':
              'Instituted to commemorate the time when the body of Jesus was taken down from the cross, anointed with spices and wrapped in linen.',
          'agpeya.eleventh_hour.latinNumber': 'XI',
          'agpeya.eleventh_hour.icon': 'assets/images/eleventh_hour.png',
          'agpeya.eleventh_hour.colorVibrant1': 'A9190D',
          'agpeya.eleventh_hour.colorVibrant2': 'D37503',
          'agpeya.eleventh_hour.colorDark': '4A2312',
          'agpeya.eleventh_hour.colorLight': 'F8E9C7',
          'agpeya.twelfth_hour.title': 'Twelfth Hour',
          'agpeya.twelfth_hour.titleLatin': 'Compline',
          'agpeya.twelfth_hour.subtitle':
              'In commemoration of the burial of Jesus Christ and our own death.',
          'agpeya.twelfth_hour.description':
              'Instituted to commemorate the laying down of the body of our Lord Jesus Christ in the tomb, also because it is the last hour of man\'s life in his das, since sleep is considered as a little death.',
          'agpeya.twelfth_hour.latinNumber': 'XII',
          'agpeya.twelfth_hour.icon': 'assets/images/twelfth_hour.png',
          'agpeya.twelfth_hour.colorVibrant1': '86312E',
          'agpeya.twelfth_hour.colorVibrant2': 'BA9F5A',
          'agpeya.twelfth_hour.colorDark': '425444',
          'agpeya.twelfth_hour.colorLight': 'D5BD8A',
          'agpeya.midnight_hour.title': 'Midnight Prayer',
          'agpeya.midnight_hour.titleLatin': 'Vigil',
          'agpeya.midnight_hour.subtitle':
              'In commemoration of the prayer vigils that Jesus Christ held in Gethsemane.',
          'agpeya.midnight_hour.description':
              'Instituted to commemorate the three times our Saviour Jesus Christ prayed in Gethsemane during His affliction on the Holy Week.',
          'agpeya.midnight_hour.latinNumber': '',
          'agpeya.midnight_hour.icon': 'assets/images/vigil_hour.png',
          'agpeya.midnight_hour.colorVibrant1': 'CD503A',
          'agpeya.midnight_hour.colorVibrant2': 'E5985E',
          'agpeya.midnight_hour.colorDark': '2F1619',
          'agpeya.midnight_hour.colorLight': 'E8B770',
        },
        'de': {
          'general.yes': 'Ja',
          'general.no': 'Nein',
          'general.close': 'Schließen',
          'general.cancel': 'Abbrechen',
          'general.save': 'Speichern',
          'general.save_changes': 'Änderungen sichern',
          'general.disable': 'Deaktivieren',
          'general.enable': 'Aktiviere',
          'general.activate': 'Aktivieren',
          'general.reset': 'Zurücksetzen',
          'general.turn_off_notifiaction': 'Benachrichtigung deaktivieren?',
          'general.edit_notification_time': 'Benachrichtigungszeit bearbeiten',
          'general.activate_notifications': 'Benachrichtigung aktivieren',
          'general.please_enable_notifications_in_the_general_settings_of_your_device':
              'Bitte aktiviere Benachrichtigungen in den allgemeinen Einstellungen deines Geräts.',
          'general.when_would_you_like_to_be_notified':
              'Wann möchten Sie benachrichtigt werden?',
          'general.daily': 'Täglich',
          'general.monday': 'Montag',
          'general.tuesday': 'Dienstag',
          'general.wednesday': 'Mittwoch',
          'general.thursday': 'Donnerstag',
          'general.friday': 'Freitag',
          'general.saturday': 'Samstag',
          'general.sunday': 'Sonntag',
          'app.title': 'Gebete',
          'settings.title': 'Einstellungen',
          'settings.dark_mode': 'Dunkelmodus',
          'settings.language': 'Sprache',
          'settings.choose_language': 'Sprache wählen',
          'agpeya.subtitle': 'Das Gebet der sieben kanonischen Stunden',
          'agpeya.title': 'Agpeya',
          'agpeya.introductory_prayer': 'Einleitungsgebet',
          'agpeya.come_and_let_us_worship': 'Kommt, lasst uns anbeten',
          'agpeya.psalms': 'Psalmen',
          'agpeya.gospel_and_litany': 'Evangelium und Litanei',
          'agpeya.trisagion_and_creed': 'Trishagion und Glaubensbekenntnis',
          'agpeya.concluding_prayers': 'Schlussgebet',
          'agpeya.hour_introduction': 'Einführungsgebet',
          'agpeya.first_service': 'Erste Andacht',
          'agpeya.second_service': 'Zweite Andacht',
          'agpeya.third_service': 'Dritte Andacht',
          'agpeya.conclusion': 'Abschließende Gebete',
          'agpeya.introduction': 'Einführung',
          'agpeya.pray_now': 'Jetzt beten',
          'agpeya.activate_this_prayer_again':
              'Dieses Gebet wieder aktivieren?',
          'agpeya.first_hour.title': 'Erste Stunde',
          'agpeya.first_hour.titleLatin': 'Prim',
          'agpeya.first_hour.subtitle':
              'Zum Gedenken an die Auferstehung Jesu Christi und zum Dank für einen neuen Tag.',
          'agpeya.first_hour.description':
              'Eingesetzt, um der Auferstehung unseres Herrn Jesus Christus von den Toten zu gedenken. Am Morgen zu beten, um Gott für den Beginn eines neuen Tages zu danken und Ihn für Seine Auferstehung zu verherrlichen.',
          'agpeya.first_hour.latinNumber': 'I',
          'agpeya.first_hour.icon': 'assets/images/first_hour.png',
          'agpeya.first_hour.colorVibrant1': '95383D',
          'agpeya.first_hour.colorVibrant2': '84529D',
          'agpeya.first_hour.colorDark': '442218',
          'agpeya.first_hour.colorLight': '442218',
          'agpeya.third_hour.title': 'Dritte Stunde',
          'agpeya.third_hour.titleLatin': 'Terz',
          'agpeya.third_hour.subtitle':
              'Zum Gedenken an die Ausgießung des Geistes und der Stunde, in der Jesus Christus verurteilt wurde.',
          'agpeya.third_hour.description':
              'Eingesetzt, um der Stunde zu gedenken, in der unser Herr Jesus Christus verurteilt wurde. Auch kam in dieser Stunde der Heilige Geist auf die Apostel herab.',
          'agpeya.third_hour.latinNumber': 'III',
          'agpeya.third_hour.icon': 'assets/images/third_hour.png',
          'agpeya.third_hour.colorVibrant1': '953622',
          'agpeya.third_hour.colorVibrant2': 'C8491C',
          'agpeya.third_hour.colorDark': '576959',
          'agpeya.third_hour.colorLight': 'FFFF83',
          'agpeya.sixth_hour.title': 'Sechste Stunde',
          'agpeya.sixth_hour.titleLatin': 'Sext',
          'agpeya.sixth_hour.subtitle':
              'Zum Gedenken an die Kreuzigung Jesu Christi um die Mittagszeit.',
          'agpeya.sixth_hour.description':
              'Eingesetzt, um der Kreuzigung unseres Herrn Jesus Christus zu gedenken.',
          'agpeya.sixth_hour.latinNumber': 'VI',
          'agpeya.sixth_hour.icon': 'assets/images/sixth_hour.png',
          'agpeya.sixth_hour.colorVibrant1': '888D35',
          'agpeya.sixth_hour.colorVibrant2': 'D05D5A',
          'agpeya.sixth_hour.colorDark': '441A1A',
          'agpeya.sixth_hour.colorLight': 'D9B46B',
          'agpeya.ninth_hour.title': 'Neunte Stunde',
          'agpeya.ninth_hour.titleLatin': 'Non',
          'agpeya.ninth_hour.subtitle':
              'Zum Gedenken an die Todesstunde, in der Jesus Christus seinen Geist aufgab.',
          'agpeya.ninth_hour.description':
              'Eingesetzt, um der Stunde des Todes unseres Herrn Jesus Christus im Fleisch zu gedenken, und des Verbrechers zu Seiner Rechten, der Gunst in Seinen Augen fand.',
          'agpeya.ninth_hour.latinNumber': 'IX',
          'agpeya.ninth_hour.icon': 'assets/images/ninth_hour.png',
          'agpeya.ninth_hour.colorVibrant1': 'AD5025',
          'agpeya.ninth_hour.colorVibrant2': '931002',
          'agpeya.ninth_hour.colorDark': '6B3012',
          'agpeya.ninth_hour.colorLight': 'DCC4A3',
          'agpeya.eleventh_hour.title': 'Elfte Stunde',
          'agpeya.eleventh_hour.titleLatin': 'Vesper',
          'agpeya.eleventh_hour.subtitle':
              'Zum Gedenken an die Kreuzabnahme Jesu Christi und der Salbung seines Leibes.',
          'agpeya.eleventh_hour.description':
              'Eingesetzt, um der Stunde zu gedenken, in der der Leib Jesu vom Kreuz abgenommen und mit wohlriechenden Ölen gesalbt und in Leinentuch eingewickelt wurde.',
          'agpeya.eleventh_hour.latinNumber': 'XI',
          'agpeya.eleventh_hour.icon': 'assets/images/eleventh_hour.png',
          'agpeya.eleventh_hour.colorVibrant1': 'A9190D',
          'agpeya.eleventh_hour.colorVibrant2': 'D37503',
          'agpeya.eleventh_hour.colorDark': '4A2312',
          'agpeya.eleventh_hour.colorLight': 'F8E9C7',
          'agpeya.twelfth_hour.title': 'Zwölfte Stunde',
          'agpeya.twelfth_hour.titleLatin': 'Komplet',
          'agpeya.twelfth_hour.subtitle':
              'Zum Gedenken an die Grablegung Jesu Christi sowie unseres eigenen Todes.',
          'agpeya.twelfth_hour.description':
              'Eingesetzt, um der Grablegung des Leibes unseres Herrn Jesus Christus zu gedenken; auch, weil es die letzte Stunde des Tages ist, denn der Schlaf ist wie ein kleiner Tod.',
          'agpeya.twelfth_hour.latinNumber': 'XII',
          'agpeya.twelfth_hour.icon': 'assets/images/twelfth_hour.png',
          'agpeya.twelfth_hour.colorVibrant1': '86312E',
          'agpeya.twelfth_hour.colorVibrant2': 'BA9F5A',
          'agpeya.twelfth_hour.colorDark': '425444',
          'agpeya.twelfth_hour.colorLight': 'D5BD8A',
          'agpeya.midnight_hour.title': 'Mitternachtsgebet',
          'agpeya.midnight_hour.titleLatin': 'Vigil',
          'agpeya.midnight_hour.subtitle':
              'Zum Gedenken an die Gebetswachen, die Jesus Christus in Gethsemane hielt.',
          'agpeya.midnight_hour.description':
              'Eingesetzt, um der drei Male zu gedenken, die unser Retter Jesus Christus während Seiner Bedrängnis in der Passionswoche in Gethsemane betete.',
          'agpeya.midnight_hour.latinNumber': '',
          'agpeya.midnight_hour.icon': 'assets/images/vigil_hour.png',
          'agpeya.midnight_hour.colorVibrant1': 'CD503A',
          'agpeya.midnight_hour.colorVibrant2': 'E5985E',
          'agpeya.midnight_hour.colorDark': '2F1619',
          'agpeya.midnight_hour.colorLight': 'E8B770',
        },
        'ar': {
          'general.yes': 'نعم',
          'general.no': 'لا',
          'general.close': 'يغلق',
          'general.cancel': 'يلغي',
          'general.save': 'يحفظ',
          'general.save_changes': 'حفظ التغييرات؟',
          'general.disable': 'إبطال',
          'general.enable': 'ممكن',
          'general.activate': 'تفعيل',
          'general.reset': 'إعادة ضبط',
          'general.turn_off_notifiaction': 'أغلق التنبيهات؟',
          'general.edit_notification_time': 'تحرير وقت الإخطار',
          'general.activate_notifications': 'إخطارات تفعيل',
          'general.please_enable_notifications_in_the_general_settings_of_your_device':
              'يرجى تمكين إخطارات في الإعدادات العامة لجهازك',
          'general.when_would_you_like_to_be_notified':
              'عندما تريد أن يتم إخطار؟',
          'general.daily': 'اليومي',
          'general.monday': 'الاثنين',
          'general.tuesday': 'يوم الثلاثاء',
          'general.wednesday': 'الأربعاء',
          'general.thursday': 'يوم الخميس',
          'general.friday': 'جمعة',
          'general.saturday': 'السبت',
          'general.sunday': 'الأحد',
          'app.title': 'صلاة',
          'settings.title': 'إعدادات',
          'settings.dark_mode': 'الوضع الظلام',
          'settings.language': 'لغة',
          'settings.choose_language': 'اختر لغة',
          'agpeya.subtitle': 'صلاة الكنسي ساعات سبعة',
          'agpeya.title': 'Agpeya',
          'agpeya.introductory_prayer': 'الصلاة التمهيدية',
          'agpeya.come_and_let_us_worship': 'هيا، دعونا العبادة',
          'agpeya.psalms': 'المزامير',
          'agpeya.gospel_and_litany': 'الإنجيل والدعاء',
          'agpeya.trisagion_and_creed': 'Trisagion تريساغيون والعقيدة',
          'agpeya.concluding_prayers': 'صلوات الختامية',
          'agpeya.hour_introduction': 'ساعة مقدمة',
          'agpeya.first_service': 'أول خدمة',
          'agpeya.second_service': 'الخدمة الثانية',
          'agpeya.third_service': 'الخدمة الثالثة',
          'agpeya.conclusion': 'استنتاج',
          'agpeya.introduction': 'مقدمة',
          'agpeya.pray_now': 'نصلي الآن',
          'agpeya.activate_this_prayer_again': 'تفعيل هذه الصلاة مرة أخرى؟',
          'agpeya.first_hour.title': 'الساعة الأولى',
          'agpeya.first_hour.titleLatin': 'أولي',
          'agpeya.first_hour.subtitle':
              'في ذكرى قيامة يسوع المسيح ولتقديم الشكر ليوم جديد.',
          'agpeya.first_hour.description':
              'وضعت للاحتفال ساعة الذي ارتفع ربنا يسوع المسيح من بين الأموات. يجب أن تقرأ في الصباح، لتقديم الشكر لله على beginnign يوم جديد، ونمجده لقيامته.',
          'agpeya.first_hour.latinNumber': 'أنا',
          'agpeya.first_hour.icon': 'assets/images/first_hour.png',
          'agpeya.first_hour.colorVibrant1': '95383D',
          'agpeya.first_hour.colorVibrant2': '84529D',
          'agpeya.first_hour.colorDark': '442218',
          'agpeya.first_hour.colorLight': '442218',
          'agpeya.third_hour.title': 'الساعة الثالثة',
          'agpeya.third_hour.titleLatin': 'Terce',
          'agpeya.third_hour.subtitle':
              'في ذكرى حلول الروح والساعة التي أدين يسوع المسيح.',
          'agpeya.third_hour.description':
              'وضعت للاحتفال ساعة الذي كان محكوما ربنا يسوع المسيح. أيضا، في هذه الساعة جاء Spririt المقدسة أسفل على التلاميذ.',
          'agpeya.third_hour.latinNumber': 'III',
          'agpeya.third_hour.icon': 'assets/images/third_hour.png',
          'agpeya.third_hour.colorVibrant1': '953622',
          'agpeya.third_hour.colorVibrant2': 'C8491C',
          'agpeya.third_hour.colorDark': '576959',
          'agpeya.third_hour.colorLight': 'FFFF83',
          'agpeya.sixth_hour.title': 'الساعة السادسة',
          'agpeya.sixth_hour.titleLatin': 'مكررا رابعا',
          'agpeya.sixth_hour.subtitle': 'في ذكرى صلب يسوع المسيح ظهرا.',
          'agpeya.sixth_hour.description':
              'وضعت لاحياء ذكرى صلب ربنا يسوع المسيح.',
          'agpeya.sixth_hour.latinNumber': 'السادس',
          'agpeya.sixth_hour.icon': 'assets/images/sixth_hour.png',
          'agpeya.sixth_hour.colorVibrant1': '888D35',
          'agpeya.sixth_hour.colorVibrant2': 'D05D5A',
          'agpeya.sixth_hour.colorDark': '441A1A',
          'agpeya.sixth_hour.colorLight': 'D9B46B',
          'agpeya.ninth_hour.title': 'تاسعا ساعة',
          'agpeya.ninth_hour.titleLatin': 'لا أحد',
          'agpeya.ninth_hour.subtitle':
              'في ذكرى ساعة الموت عندما أعطى يسوع المسيح حتى روحه.',
          'agpeya.ninth_hour.description':
              'وضعت للاحتفال ساعة الموت ربنا يسوع المسيح في الجسد، والسارق اليمنى الذي وجدت نعمة في عينيه.',
          'agpeya.ninth_hour.latinNumber': 'IX',
          'agpeya.ninth_hour.icon': 'assets/images/ninth_hour.png',
          'agpeya.ninth_hour.colorVibrant1': 'AD5025',
          'agpeya.ninth_hour.colorVibrant2': '931002',
          'agpeya.ninth_hour.colorDark': '6B3012',
          'agpeya.ninth_hour.colorLight': 'DCC4A3',
          'agpeya.eleventh_hour.title': 'الحادي عشر Stunde',
          'agpeya.eleventh_hour.titleLatin': 'صلاة المساء',
          'agpeya.eleventh_hour.subtitle':
              'في ذكرى اتخاذ بانخفاض يسوع المسيح عن الصليب ومسحة من جسده.',
          'agpeya.eleventh_hour.description':
              'وضعت للاحتفال الوقت الذي أخذ جسد يسوع ينزل عن الصليب، مسحه مع التوابل وملفوفة في الكتان.',
          'agpeya.eleventh_hour.latinNumber': 'XI',
          'agpeya.eleventh_hour.icon': 'assets/images/eleventh_hour.png',
          'agpeya.eleventh_hour.colorVibrant1': 'A9190D',
          'agpeya.eleventh_hour.colorVibrant2': 'D37503',
          'agpeya.eleventh_hour.colorDark': '4A2312',
          'agpeya.eleventh_hour.colorLight': 'F8E9C7',
          'agpeya.twelfth_hour.title': 'الثاني عشر ساعة',
          'agpeya.twelfth_hour.titleLatin': 'Compline',
          'agpeya.twelfth_hour.subtitle':
              'في ذكرى دفن يسوع المسيح والموت الخاصة بنا.',
          'agpeya.twelfth_hour.description':
              'وضعت للاحتفال وضع جسد ربنا يسوع المسيح في القبر، وأيضا لأنها الساعة الأخيرة من حياة الإنسان في داس له، حيث تعتبر النوم كما قليلا الموت.',
          'agpeya.twelfth_hour.latinNumber': 'XII',
          'agpeya.twelfth_hour.icon': 'assets/images/twelfth_hour.png',
          'agpeya.twelfth_hour.colorVibrant1': '86312E',
          'agpeya.twelfth_hour.colorVibrant2': 'BA9F5A',
          'agpeya.twelfth_hour.colorDark': '425444',
          'agpeya.twelfth_hour.colorLight': 'D5BD8A',
          'agpeya.midnight_hour.title': 'الصلاة منتصف الليل',
          'agpeya.midnight_hour.titleLatin': 'يقظة',
          'agpeya.midnight_hour.subtitle':
              'في ذكرى الوقفات الاحتجاجية صلاة يسوع المسيح الذي عقد في الجسمانية.',
          'agpeya.midnight_hour.description':
              'وضعت لإحياء ثلاث مرات مخلصنا يسوع المسيح يصلي في بستان الزيتون خلال صاحب فتنة في أسبوع الآلام.',
          'agpeya.midnight_hour.latinNumber': '',
          'agpeya.midnight_hour.icon': 'assets/images/vigil_hour.png',
          'agpeya.midnight_hour.colorVibrant1': 'CD503A',
          'agpeya.midnight_hour.colorVibrant2': 'E5985E',
          'agpeya.midnight_hour.colorDark': '2F1619',
          'agpeya.midnight_hour.colorLight': 'E8B770',
        },
        'ko': {
          'general.yes': '예',
          'general.no': '아니',
          'general.close': '닫기',
          'general.cancel': '취소',
          'general.save': '저장',
          'general.save_changes': '변경 사항을 저장하다?',
          'general.disable': '사용 안 함',
          'general.enable': '사용',
          'general.activate': '활성화',
          'general.reset': '초기화',
          'general.turn_off_notifiaction': '알림 사용 중지 하시겠습니까?',
          'general.edit_notification_time': '편집 알림 시간',
          'general.activate_notifications': '활성화 통지',
          'general.please_enable_notifications_in_the_general_settings_of_your_device':
              '장치의 일반 설정에서 알림을 사용하시기 바랍니다',
          'general.when_would_you_like_to_be_notified': '언제 통보 하시겠습니까?',
          'general.daily': '매일',
          'general.monday': '월요일',
          'general.tuesday': '화요일',
          'general.wednesday': '수요일',
          'general.thursday': '목요일',
          'general.friday': '금요일',
          'general.saturday': '토요일',
          'general.sunday': '일요일',
          'app.title': '기도',
          'settings.title': '설정',
          'settings.dark_mode': '다크 모드',
          'settings.language': '언어',
          'settings.choose_language': '언어를 선택',
          'agpeya.subtitle': '일곱 정규 시간의기도',
          'agpeya.title': 'Agpeya',
          'agpeya.introductory_prayer': '입문기도',
          'agpeya.come_and_let_us_worship': '자, 우리가 경배하자',
          'agpeya.psalms': '시편',
          'agpeya.gospel_and_litany': '복음과 기도서',
          'agpeya.trisagion_and_creed': 'Trisagion 및 신조',
          'agpeya.concluding_prayers': '결론기도',
          'agpeya.hour_introduction': '시간 소개',
          'agpeya.first_service': '먼저 서비스',
          'agpeya.second_service': '두 번째 서비스',
          'agpeya.third_service': '셋째 서비스',
          'agpeya.conclusion': '결론',
          'agpeya.introduction': '소개',
          'agpeya.pray_now': '기도 해주기',
          'agpeya.activate_this_prayer_again': '다시기도를 활성화?',
          'agpeya.first_hour.title': '첫 번째 시간',
          'agpeya.first_hour.titleLatin': '초기',
          'agpeya.first_hour.subtitle': '예수 그리스도의 부활을 기념 새로운 날에 대한 감사를 제공합니다.',
          'agpeya.first_hour.description':
              '우리 주 예수 그리스도 께서 죽음에서 부활하는 시간을 기념하기 위해 제정. 새로운 하루의 beginnign 하나님 께 감사를드립니다하고, 그분의 부활을 위해 하나님을 영화 롭게하기 위해, 아침에 읽을 수있다.',
          'agpeya.first_hour.latinNumber': '나는',
          'agpeya.first_hour.icon': 'assets/images/first_hour.png',
          'agpeya.first_hour.colorVibrant1': '95383D',
          'agpeya.first_hour.colorVibrant2': '84529D',
          'agpeya.first_hour.colorDark': '442218',
          'agpeya.first_hour.colorLight': '442218',
          'agpeya.third_hour.title': '세 번째 시간',
          'agpeya.third_hour.titleLatin': 'Terce',
          'agpeya.third_hour.subtitle': '성령의 부어 주심과 예수 그리스도 께서 정죄하는 시간을 기념.',
          'agpeya.third_hour.description':
              '우리 주 예수 그리스도 께서 정죄하는 시간을 기념하기 위해 제정. 또한,이 시간에 성령 Spririt 제자에 내려왔다.',
          'agpeya.third_hour.latinNumber': 'III',
          'agpeya.third_hour.icon': 'assets/images/third_hour.png',
          'agpeya.third_hour.colorVibrant1': '953622',
          'agpeya.third_hour.colorVibrant2': 'C8491C',
          'agpeya.third_hour.colorDark': '576959',
          'agpeya.third_hour.colorLight': 'FFFF83',
          'agpeya.sixth_hour.title': '여섯 번째 시간',
          'agpeya.sixth_hour.titleLatin': 'Sext',
          'agpeya.sixth_hour.subtitle': '정오에 예수 그리스도의 십자가 기념.',
          'agpeya.sixth_hour.description': '우리 주 예수 그리스도의 십자가를 기념하기 위해 제정.',
          'agpeya.sixth_hour.latinNumber': 'VI',
          'agpeya.sixth_hour.icon': 'assets/images/sixth_hour.png',
          'agpeya.sixth_hour.colorVibrant1': '888D35',
          'agpeya.sixth_hour.colorVibrant2': 'D05D5A',
          'agpeya.sixth_hour.colorDark': '441A1A',
          'agpeya.sixth_hour.colorLight': 'D9B46B',
          'agpeya.ninth_hour.title': '아홉 번째 시간',
          'agpeya.ninth_hour.titleLatin': '없음',
          'agpeya.ninth_hour.subtitle': '죽음의 시간을 기념 예수 그리스도는 성령을 받았습니다.',
          'agpeya.ninth_hour.description':
              '육체를 우리 주 예수 그리스도의 죽음의 시간, 그리고 그의 눈에 호의를 발견 오른쪽 도둑을 기념하기 위해 제정.',
          'agpeya.ninth_hour.latinNumber': 'IX',
          'agpeya.ninth_hour.icon': 'assets/images/ninth_hour.png',
          'agpeya.ninth_hour.colorVibrant1': 'AD5025',
          'agpeya.ninth_hour.colorVibrant2': '931002',
          'agpeya.ninth_hour.colorDark': '6B3012',
          'agpeya.ninth_hour.colorLight': 'DCC4A3',
          'agpeya.eleventh_hour.title': '열한번째 Stunde',
          'agpeya.eleventh_hour.titleLatin': '저녁 예배',
          'agpeya.eleventh_hour.subtitle':
              '십자가에서 예수 그리스도의 복용과 그의 몸의 기름 부음의 기념.',
          'agpeya.eleventh_hour.description':
              '예수님의 몸은 십자가에서 내려올 향신료와 기름 부음과 리넨에 싸여 된 시간을 기념하기 위해 제정.',
          'agpeya.eleventh_hour.latinNumber': 'XI',
          'agpeya.eleventh_hour.icon': 'assets/images/eleventh_hour.png',
          'agpeya.eleventh_hour.colorVibrant1': 'A9190D',
          'agpeya.eleventh_hour.colorVibrant2': 'D37503',
          'agpeya.eleventh_hour.colorDark': '4A2312',
          'agpeya.eleventh_hour.colorLight': 'F8E9C7',
          'agpeya.twelfth_hour.title': '열두 번째 시간',
          'agpeya.twelfth_hour.titleLatin': 'Compline',
          'agpeya.twelfth_hour.subtitle': '예수 그리스도와 우리 자신의 죽음의 매장을 기념.',
          'agpeya.twelfth_hour.description':
              '그것은 그의 다스에서 인간의 삶의 마지막 시간이기 때문에 잠이 조금 죽음으로 간주되기 때문에, 또한, 무덤에 누워 아래로 우리 주 예수 그리스도의 몸을 기념하기 위해 제정.',
          'agpeya.twelfth_hour.latinNumber': 'XII',
          'agpeya.twelfth_hour.icon': 'assets/images/twelfth_hour.png',
          'agpeya.twelfth_hour.colorVibrant1': '86312E',
          'agpeya.twelfth_hour.colorVibrant2': 'BA9F5A',
          'agpeya.twelfth_hour.colorDark': '425444',
          'agpeya.twelfth_hour.colorLight': 'D5BD8A',
          'agpeya.midnight_hour.title': '자정기도',
          'agpeya.midnight_hour.titleLatin': '철야 기도',
          'agpeya.midnight_hour.subtitle': '예수 그리스도 께서 겟세마네에서 열린기도 집회의 기념.',
          'agpeya.midnight_hour.description':
              '성령 주에 대한 그의 고난 중에 우리 구주 예수 그리스도 께서 겟세마네에서기도 세 번을 기념하기 위해 제정.',
          'agpeya.midnight_hour.latinNumber': '',
          'agpeya.midnight_hour.icon': 'assets/images/vigil_hour.png',
          'agpeya.midnight_hour.colorVibrant1': 'CD503A',
          'agpeya.midnight_hour.colorVibrant2': 'E5985E',
          'agpeya.midnight_hour.colorDark': '2F1619',
          'agpeya.midnight_hour.colorLight': 'E8B770',
        },
      };
}
